### ISSUE TITLE
support for roam app? 

### ISSUE THREAD

**Issue by giovannicoppola** [jacrify/RoamPageSearch#4]
Hi @jacrify, we were in touch on slack when you first developed this. I think it is still the best out there and I was wondering if you plan to add support for the app? I'd be happy to help if you are.

**Comment by jacrify** [comment]
I moved to obsidian dude. I’m pretty unlikely to spend any time on it. I’m
happy to gift the code to you, do a walkthrough, answer questions etc. It’s
a pretty cool thing. The implementation is pretty dodgy in places though.

**Comment by giovannicoppola** [comment]
thanks! I will fork it for now and think about it. I use obsidian too for stuff that needs to be local... I hope you are well.

**Comment by jacrify** [comment]
If you decide to take it on I’m happy to spend a couple of hours on video
walking you through.

I’m good mate.👍
